
# Introduction to NumPy for AI

Welcome to this fun and engaging lesson on **NumPy**, one of the most important libraries in Python for AI and data analysis. In this notebook, we'll learn how to use NumPy with a dataset related to **cricket players** and then with dataset related to **Olympic Medal Analysis**, and we'll perform exploratory analysis using NumPy.

Let's get started! 🎉
    

In [5]:

# Step 1: Importing NumPy
import numpy as np

# Print a welcome message
print("Welcome to NumPy - The Foundation of AI and Data Analysis!")

Welcome to NumPy - The Foundation of AI and Data Analysis!



## Step 2: Create a Fun Dataset

Here, we create a dataset to analyze the performance of players in a cricket tournament. The dataset includes runs scored by 5 players across 3 matches.
    

In [17]:
x = np.random.randint(1,1000,size=(4000,1000))
x

array([[726, 628, 604, ..., 882,  14, 178],
       [412, 878,  53, ..., 166, 657, 842],
       [370, 795,  54, ..., 406, 608, 422],
       ...,
       [238, 898, 895, ..., 450, 866, 663],
       [891, 734, 754, ..., 367, 722, 446],
       [825, 719, 770, ..., 991, 400, 295]], dtype=int32)

In [8]:
# Create a dataset: Runs scored by 5 players in 3 matches
players = np.array(['Sachin', 'Virat Kohli', 'Yashasvi', 'Jaspreet', 'Rishab'])
matches = np.array(['IPL 2015', 'IPL 2020', 'IPL 2023'])

# Randomly generate runs scored by players
#np.random.seed(42)  # For reproducibility
runs = np.random.randint(10, 100, size=(len(players), len(matches)))

# Print the dataset
print("Players:", players)
print("Matches:", matches)
print("Runs scored by each player:")
print(runs)

Players: ['Sachin' 'Virat Kohli' 'Yashasvi' 'Jaspreet' 'Rishab']
Matches: ['IPL 2015' 'IPL 2020' 'IPL 2023']
Runs scored by each player:
[[61 24 81]
 [70 30 92]
 [96 84 84]
 [97 33 12]
 [31 62 11]]



## Step 3: Summing Up the Runs
Using np.sum, we calculate the total runs scored by each player across all matches.
    

In [11]:
# Calculate total runs scored by each player
total_runs_by_player = runs.sum(axis=1)
print("Total runs scored by each player:")
for player, total in zip(players, total_runs_by_player):
    print(f"{player}: {total} runs")

Total runs scored by each player:
Sachin: 166 runs
Virat Kohli: 192 runs
Yashasvi: 264 runs
Jaspreet: 142 runs
Rishab: 104 runs



## Step 4: Average Runs Per Match
We calculate the average runs scored per match by all players.

In [ ]:
# Calculate average runs per match
average_runs_per_match = runs.mean(axis=0)
print("Average runs scored in each match:")
for match, avg in zip(matches, average_runs_per_match):
    print(f"{match}: {avg:.2f} runs")


## Step 5: Player with the Most Runs
Using np.argmax, we find the player with the most total runs.
    

In [ ]:
# Find the player with the highest total runs
most_runs_index = np.argmax(total_runs_by_player)
print(f"The player with the most runs is {players[most_runs_index]} with {total_runs_by_player[most_runs_index]} runs.")


## Step 6: Variability in Scores
The standard deviation tells us how consistent players are. A low standard deviation means consistent performance, while a high value indicates variability.
    

In [ ]:
# Calculate the standard deviation of runs for each player
std_dev_by_player = runs.std(axis=1)
print("Variability in performance (Standard Deviation):")
for player, std in zip(players, std_dev_by_player):
    print(f"{player}: {std:.2f}")


## Step 7: Visualizing the Data
Let’s create a bar chart to show the total runs scored by each player.
    

In [ ]:
# Import matplotlib for plotting
import matplotlib.pyplot as plt

# Bar chart of total runs by player
plt.figure(figsize=(8, 5))
plt.bar(players, total_runs_by_player, color='skyblue')
plt.title("Total Runs Scored by Each Player")
plt.xlabel("Players")
plt.ylabel("Total Runs")
plt.show()


## Step 8: Why These Metrics Matter
Sum of Runs: Identifies the top-performing players.<p>
Average Runs: Highlights overall team performance trends.<p>
Standard Deviation: Shows how consistent a player is.<p>
Understanding these figures is important for AI because similar concepts are used in analyzing data and making predictions.
    


## Step 9: Create a another Fun Dataset

We'll create a dataset to analyze the performance of countries in the Olympics over several years.
    

In [ ]:

# Create a dataset: Olympic medals for 5 countries over 4 years
countries = np.array(['USA', 'China', 'India', 'Germany', 'Australia'])
years = np.array([2012, 2016, 2020, 2024])  # Olympic years

# Randomly generate the number of medals (Gold, Silver, Bronze) for each country in each year
np.random.seed(42)  # For reproducibility
medals = np.random.randint(10, 100, size=(len(countries), len(years), 3))  # 3 types of medals

# Print the dataset
print("Countries:", countries)
print("Years:", years)
print("Medals (Gold, Silver, Bronze):")
print(medals)


## Step 10: Analyzing the Data

Now, let's use NumPy to perform some basic analysis and calculate important statistics.
    

In [ ]:

# Total medals won by each country
total_medals_by_country = medals.sum(axis=2)  # Sum across medal types
print("Total medals by each country over the years:")
for country, total in zip(countries, total_medals_by_country):
    print(f"{country}: {total}")

In [ ]:

# Which country won the most medals in 2020?
medals_2020 = total_medals_by_country[:, 2]  # Medals in the 3rd year (2020)
most_medals_index = np.argmax(medals_2020)
print(f"Country with the most medals in 2020: {countries[most_medals_index]} ({medals_2020[most_medals_index]} medals)")

In [ ]:

# Average medals by year
average_medals_by_year = total_medals_by_country.mean(axis=0)
print("Average medals won by all countries in each year:")
for year, avg in zip(years, average_medals_by_year):
    print(f"{year}: {avg:.2f}")

In [ ]:

# Standard deviation of medals (measure of variability)
std_dev_by_year = total_medals_by_country.std(axis=0)
print("Standard deviation of medals won by all countries in each year:")
for year, std in zip(years, std_dev_by_year):
    print(f"{year}: {std:.2f}")


## Step 11: Visualization (Optional Fun!)

Let's visualize the data to make it more interesting.
    

In [ ]:

import matplotlib.pyplot as plt

# Plot total medals for each country
plt.figure(figsize=(10, 6))
for i, country in enumerate(countries):
    plt.plot(years, total_medals_by_country[i], label=country, marker='o')

plt.title('Total Olympic Medals by Country Over Years')
plt.xlabel('Year')
plt.ylabel('Total Medals')
plt.legend()
plt.grid(True)
plt.show()


## Step 12: Why These Metrics Matter

- **Sum of Medals**: Helps identify top-performing countries.

- **Average Medals**: Indicates the overall trend in performance.

- **Standard Deviation**: Shows the consistency or variability in performance.


Understanding these figures is crucial in AI as they often form the basis of decision-making systems or predictive models.
    


## Wrap-Up

Congratulations! 🎉 You've learned how to use NumPy for exploratory data analysis. 
You've also explored how data analysis is important for gaining insights, which is a key step in building AI models.

Feel free to tweak the data and explore more on your own. Happy learning! 🚀
    